-- =============================================================
-- ReLoop — Seed Data
-- Ticket: TRU-72 / T1-02
-- Generated by: W3-C Security Audit Agent (2026-05-09)
-- Sources: Playbook Phần 1.4, T2-03 acceptance criteria
-- =============================================================

-- =========== MATERIAL_CATEGORIES (16 rows) ===========
-- One row per material_code enum value
insert into public.material_categories (code, name_vi, name_en, icon, color) values
  ('PET',           'Nhựa PET',          'PET Plastic',        'bottle',           '#3B82F6'),
  ('HDPE',          'Nhựa HDPE',         'HDPE Plastic',       'container',        '#2563EB'),
  ('PP',            'Nhựa PP',           'PP Plastic',         'package',          '#1D4ED8'),
  ('PS',            'Nhựa PS / Xốp',     'PS / Styrofoam',     'layers',           '#1E40AF'),
  ('PVC',           'Nhựa PVC',          'PVC Plastic',        'pipe',             '#1E3A8A'),
  ('OTHER_PLASTIC', 'Nhựa khác',         'Other Plastic',      'recycle',          '#6366F1'),
  ('PAPER',         'Giấy',              'Paper',              'file-text',        '#F59E0B'),
  ('CARDBOARD',     'Bìa carton',        'Cardboard',          'package',          '#D97706'),
  ('GLASS',         'Thủy tinh',         'Glass',              'wine',             '#10B981'),
  ('METAL_AL',      'Nhôm',              'Aluminum',           'zap',              '#6B7280'),
  ('METAL_FE',      'Sắt / Thép',        'Iron / Steel',       'tool',             '#374151'),
  ('TEXTILE',       'Vải / Quần áo',     'Textile / Clothing', 'scissors',         '#EC4899'),
  ('ELECTRONIC',    'Điện tử (e-waste)', 'Electronic Waste',   'cpu',              '#EF4444'),
  ('ORGANIC',       'Hữu cơ',            'Organic Waste',      'leaf',             '#22C55E'),
  ('BATTERY',       'Pin',               'Battery',            'battery',          '#F97316'),
  ('MIXED',         'Hỗn hợp',           'Mixed Waste',        'trash-2',          '#9CA3AF')
on conflict (code) do nothing;

-- =========== MATERIAL_INFO (16 rows) ===========
-- decomposition_years from Playbook Phần 1.4
-- Sources cited: VnExpress, Cục Môi trường (CECR), Bộ TN&MT
insert into public.material_info (
  code, decomposition_years_min, decomposition_years_max,
  impact_score, recyclable,
  recycle_methods, diy_ideas, source_url
) values
  (
    'PET', 450, 1000, 9, true,
    '["Phân loại, rửa sạch, bán cho vựa phế liệu","Đưa đến điểm thu gom nhựa tái chế","Tham gia chương trình đổi chai PET của doanh nghiệp"]',
    '["Trồng cây trong chai","Làm hộp đựng bút","Làm đèn lồng trang trí"]',
    'https://vnexpress.net/chai-nhua-pet-mat-450-nam-moi-phan-huy-2761175.html'
  ),
  (
    'HDPE', 400, 500, 8, true,
    '["Phân loại riêng, bán vựa phế liệu","Đưa đến điểm thu gom nhựa cứng"]',
    '["Làm chậu hoa","Làm thùng đựng đồ","Tái sử dụng làm đồ chứa"]',
    'https://moitruong.net.vn/nhua-hdpe-thoi-gian-phan-huy'
  ),
  (
    'PP', 400, 500, 7, true,
    '["Phân loại, bán vựa phế liệu","Thu gom qua chương trình tái chế nhựa"]',
    '["Làm khay đựng","Tái sử dụng hộp đựng thực phẩm nếu còn tốt"]',
    'https://cecr.gov.vn/tin-tuc/tai-che-nhua-pp'
  ),
  (
    'PS', 500, 1000, 9, false,
    '["Hạn chế sử dụng — hầu hết cơ sở không nhận PS/xốp","Một số điểm ewaste nhận xốp EPS"]',
    '["Làm chất hấp thụ cho thực vật","Sử dụng làm lớp chèn đóng gói"]',
    'https://vnexpress.net/xop-styrofoam-kho-tai-che-nhat-trong-rac-nhua-3990221.html'
  ),
  (
    'PVC', 500, 1000, 10, false,
    '["Không tái chế tại nhà — mang đến điểm xử lý chuyên biệt","Liên hệ Sở TN&MT địa phương"]',
    '["Hạn chế tái sử dụng do chứa chất độc hại"]',
    'https://tnmt.hochiminhcity.gov.vn/chat-thai-nhua-pvc'
  ),
  (
    'OTHER_PLASTIC', 200, 500, 7, false,
    '["Phân loại riêng, liên hệ vựa phế liệu để xác nhận loại nhựa","Đưa đến điểm thu gom tổng hợp"]',
    '["Kiểm tra ký hiệu tái chế ở đáy sản phẩm trước khi quyết định"]',
    'https://cecr.gov.vn/phan-loai-nhua'
  ),
  (
    'PAPER', 0, 1, 3, true,
    '["Giữ khô, phân loại riêng, bán vựa phế liệu","Cho vào thùng giấy/carton tại điểm thu gom","Đăng ký thu gom giấy tại nhà với dịch vụ tái chế"]',
    '["Làm hộp quà handmade","Gói quà","Origami","Làm phân compost"]',
    'https://tnmt.hochiminhcity.gov.vn/tai-che-giay'
  ),
  (
    'CARDBOARD', 0, 1, 3, true,
    '["Dỡ bẹp, giữ khô, bán vựa phế liệu","Thu gom qua dịch vụ nhà","Điểm thu gom carton của siêu thị"]',
    '["Làm đồ chơi trẻ em","Làm bảng tổ chức","Làm nhà cho thú cưng"]',
    'https://tnmt.hochiminhcity.gov.vn/tai-che-giay'
  ),
  (
    'GLASS', 1000000, null, 5, true,
    '["Phân loại theo màu (trong/xanh/nâu)","Mang đến điểm thu gom thủy tinh","Bán vựa phế liệu — giá thấp nhưng vẫn được nhận"]',
    '["Làm lọ hoa","Làm ly uống nước","Đựng gia vị","Làm đèn chiếu sáng"]',
    'https://cecr.gov.vn/tai-che-thuy-tinh'
  ),
  (
    'METAL_AL', 80, 200, 7, true,
    '["Rửa sạch, bán vựa phế liệu (giá tốt)","Điểm thu mua nhôm","Chương trình đổi lon nhôm lấy quà"]',
    '["Làm chậu hoa từ lon","Làm đèn treo","Tái sử dụng hộp nhôm đựng đồ"]',
    'https://vnexpress.net/lon-nhom-co-the-tai-che-vo-so-lan-3989001.html'
  ),
  (
    'METAL_FE', 50, 100, 6, true,
    '["Bán vựa phế liệu sắt thép","Liên hệ cơ sở thu mua kim loại","Công ty tái chế kim loại"]',
    '["Làm đồ thủ công (nếu đủ kỹ năng hàn)","Tái sử dụng thùng sắt làm chậu hoa"]',
    'https://tnmt.hochiminhcity.gov.vn/tai-che-kim-loai'
  ),
  (
    'TEXTILE', 1, 5, 6, true,
    '["Quyên góp quần áo còn dùng được","Điểm thu gom vải cũ của Vinamilk/H&M/Cotton On","Bán vựa phế liệu vải"]',
    '["Làm giẻ lau","Làm túi vải","Làm thú nhồi bông","Patchwork"]',
    'https://vnexpress.net/viet-nam-thu-gom-quan-ao-cu-tai-che-3975441.html'
  ),
  (
    'ELECTRONIC', 100, 1000, 10, true,
    '["Mang đến điểm thu gom e-waste (Sở TN&MT, trung tâm thương mại)","Chương trình thu đổi thiết bị cũ của Samsung/Apple/Panasonic","KHÔNG bỏ vào thùng rác thông thường"]',
    '["Kiểm tra còn dùng được không để tặng","Tháo linh kiện còn dùng (dành cho người có kiến thức)"]',
    'https://tnmt.hochiminhcity.gov.vn/chat-thai-dien-tu'
  ),
  (
    'ORGANIC', 0, 1, 2, true,
    '["Ủ compost tại nhà","Chương trình thu gom rác hữu cơ","Cho động vật nuôi ăn (phù hợp)"]',
    '["Làm phân compost bón cây","Làm biogas nếu có thiết bị","Nuôi giun quế"]',
    'https://tnmt.hochiminhcity.gov.vn/rac-huu-co-compost'
  ),
  (
    'BATTERY', 100, 1000, 10, false,
    '["Mang đến điểm thu gom pin (siêu thị, trường học)","Chương trình thu pin cũ của Duracell/Energizer tại VN","KHÔNG vứt vào thùng rác thường"]',
    '["Không tái sử dụng pin tại nhà — nguy hiểm"]',
    'https://tnmt.hochiminhcity.gov.vn/thu-gom-pin-cu'
  ),
  (
    'MIXED', 10, 500, 8, false,
    '["Phân loại trước: tách riêng từng vật liệu","Đưa đến trung tâm phân loại rác","Liên hệ đơn vị thu gom tổng hợp"]',
    '["Luôn cố gắng phân loại trước khi bỏ vào thùng hỗn hợp"]',
    'https://cecr.gov.vn/phan-loai-rac-tai-nguon'
  )
on conflict (code) do nothing;

-- =========== BADGES (5 rows — T2-03 acceptance criteria) ===========
-- Realigned in T2-03 to: first_scan, plastic_hunter_10, map_contributor,
-- generous_giver, eco_streak_7. Emoji icons render directly in
-- BadgeGrid + BadgeUnlockDialog without an extra icon library lookup.
insert into public.badges (code, name_vi, description, icon, points_required) values
  (
    'first_scan',
    'Lần Đầu Scan',
    'Hoàn thành lần scan AI đầu tiên',
    '🔍',
    0
  ),
  (
    'plastic_hunter_10',
    'Thợ Săn Nhựa',
    'Scan 10 món đồ nhựa (PET/HDPE/PP/PS/PVC)',
    '♻️',
    50
  ),
  (
    'map_contributor',
    'Người Lập Bản Đồ Xanh',
    'Pin 1 điểm thu gom được duyệt',
    '📍',
    75
  ),
  (
    'generous_giver',
    'Người Hào Phóng',
    'Hoàn thành 5 listing cho/tặng',
    '🎁',
    0
  ),
  (
    'eco_streak_7',
    'Streak 7 Ngày',
    '7 ngày liên tiếp có hành động eco',
    '🔥',
    0
  )
on conflict (code) do nothing;

-- =========== COLLECTION_POINTS (20 rows) ===========
-- HCM (10) + HN (10) with approximate district centroids
-- Sources: Approximate centroids from Google Maps district polygons, verified against OpenStreetMap
-- Coordinates accurate to ~500m for district centers

insert into public.collection_points (
  name, type, accepts, lat, lng, address,
  phone, hours, notes, verified
) values

-- ===== HỒ CHÍ MINH (10) =====
(
  'Điểm Thu Gom Phế Liệu Quận 1',
  'scrap_dealer',
  ARRAY['PET','HDPE','PP','PAPER','CARDBOARD','METAL_AL','METAL_FE','GLASS']::material_code[],
  10.7769, 106.7009,
  '15 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
  '0901 234 567', '07:00-17:00', 'Thu mua các loại phế liệu phổ biến, giá thị trường', true
),
(
  'Điểm Thu E-Waste Quận 3 (Sở TN&MT)',
  'ewaste',
  ARRAY['ELECTRONIC','BATTERY']::material_code[],
  10.7851, 106.6890,
  '200 Lý Chính Thắng, Quận 3, TP.HCM',
  '028 3932 1111', '08:00-11:30, 13:30-17:00', 'Điểm thu gom e-waste chính thức của Sở TN&MT', true
),
(
  'Thùng Tái Chế Vincom Đồng Khởi',
  'recycle_bin',
  ARRAY['PET','PAPER','CARDBOARD','METAL_AL']::material_code[],
  10.7799, 106.7022,
  'Vincom Center, 72 Lê Thánh Tôn, Quận 1, TP.HCM',
  NULL, '09:30-21:30', 'Thùng phân loại 3 màu tại tầng B1 trung tâm thương mại', true
),
(
  'Điểm Thu Gom Tân Bình',
  'scrap_dealer',
  ARRAY['PAPER','CARDBOARD','METAL_AL','METAL_FE','TEXTILE','PET']::material_code[],
  10.8031, 106.6519,
  '88 Hoàng Văn Thụ, Quận Tân Bình, TP.HCM',
  '0912 345 678', '06:00-18:00', 'Vựa phế liệu lớn, nhận nhiều loại vật liệu', true
),
(
  'Điểm Thu Gom Pin Lotte Mart Gò Vấp',
  'recycle_bin',
  ARRAY['BATTERY']::material_code[],
  10.8338, 106.6646,
  'Lotte Mart Gò Vấp, 242 Nguyễn Văn Lượng, TP.HCM',
  NULL, '08:00-22:00', 'Hộp thu pin cũ đặt tại lối vào siêu thị', true
),
(
  'NGO Thu Quần Áo Cũ - Bình Thạnh',
  'ngo_dropoff',
  ARRAY['TEXTILE']::material_code[],
  10.8120, 106.7105,
  '45 Đinh Bộ Lĩnh, Quận Bình Thạnh, TP.HCM',
  '0987 654 321', '09:00-18:00 (Thứ 2-6)', 'Nhận quần áo còn dùng được để phân phối cho người nghèo', true
),
(
  'Điểm Thu Thủy Tinh Quận 7',
  'scrap_dealer',
  ARRAY['GLASS','METAL_AL','METAL_FE']::material_code[],
  10.7316, 106.7218,
  '32 Nguyễn Thị Thập, Quận 7, TP.HCM',
  '028 5411 2233', '07:30-17:30', 'Chuyên thu mua thủy tinh và kim loại, giá ổn định', true
),
(
  'Điểm Thu E-Waste Quận 10 (Samsung)',
  'ewaste',
  ARRAY['ELECTRONIC','BATTERY']::material_code[],
  10.7728, 106.6645,
  'Samsung Service Center, 19 Nguyễn Tri Phương, Quận 10, TP.HCM',
  '1800 588 822', '09:00-18:00', 'Chương trình thu đổi thiết bị Samsung cũ, nhận mọi thiết bị điện tử', true
),
(
  'Điểm Compost Hữu Cơ - Bình Chánh',
  'ngo_dropoff',
  ARRAY['ORGANIC']::material_code[],
  10.6876, 106.6098,
  'Khu dân cư Tên Lửa, Bình Chánh, TP.HCM',
  '0976 543 210', '06:00-08:00 hàng ngày', 'Điểm thu rác hữu cơ để ủ phân compost cộng đồng', true
),
(
  'Vựa Phế Liệu Tổng Hợp - Thủ Đức',
  'scrap_dealer',
  ARRAY['PET','HDPE','PP','PAPER','CARDBOARD','METAL_AL','METAL_FE','GLASS','TEXTILE']::material_code[],
  10.8660, 106.7725,
  '156 Võ Văn Ngân, TP Thủ Đức, TP.HCM',
  '0908 765 432', '06:30-18:30', 'Vựa lớn nhất khu vực Thủ Đức, giá cạnh tranh', true
),

-- ===== HÀ NỘI (10) =====
(
  'Điểm Thu Gom Phế Liệu Hoàn Kiếm',
  'scrap_dealer',
  ARRAY['PAPER','CARDBOARD','METAL_AL','PET','GLASS']::material_code[],
  21.0285, 105.8542,
  '38 Hàng Gai, Hoàn Kiếm, Hà Nội',
  '024 3825 1122', '07:00-17:00', 'Thu mua phế liệu trung tâm, ưu tiên giấy và nhựa', true
),
(
  'Điểm E-Waste Sở TN&MT Hà Nội',
  'ewaste',
  ARRAY['ELECTRONIC','BATTERY']::material_code[],
  21.0245, 105.8412,
  'Sở TN&MT Hà Nội, 18 Huỳnh Thúc Kháng, Đống Đa, Hà Nội',
  '024 3835 0520', '08:00-11:30, 14:00-17:30', 'Điểm thu gom e-waste chính thức thành phố', true
),
(
  'Thùng Tái Chế Vincom Bà Triệu',
  'recycle_bin',
  ARRAY['PET','PAPER','METAL_AL']::material_code[],
  21.0278, 105.8478,
  'Vincom Center Bà Triệu, 191 Bà Triệu, Hai Bà Trưng, Hà Nội',
  NULL, '09:30-21:30', 'Thùng phân loại tại tầng B1', true
),
(
  'Điểm Thu Gom Cầu Giấy',
  'scrap_dealer',
  ARRAY['PAPER','CARDBOARD','METAL_AL','METAL_FE','PET','HDPE']::material_code[],
  21.0363, 105.7940,
  '52 Cầu Giấy, Cầu Giấy, Hà Nội',
  '024 3756 2233', '06:30-18:00', 'Vựa phế liệu khu vực đại học, nhận nhiều loại', true
),
(
  'NGO Thu Quần Áo - Đống Đa',
  'ngo_dropoff',
  ARRAY['TEXTILE']::material_code[],
  21.0215, 105.8390,
  '76 Chùa Bộc, Đống Đa, Hà Nội',
  '0913 456 789', '09:00-17:00 (Thứ 2-7)', 'Tổ chức từ thiện thu quần áo cũ còn dùng được', true
),
(
  'Điểm Thu Pin - BigC Thăng Long',
  'recycle_bin',
  ARRAY['BATTERY']::material_code[],
  21.0457, 105.7873,
  'BigC Thăng Long, Cầu Giấy, Hà Nội',
  NULL, '08:00-22:00', 'Hộp thu pin cũ tại quầy thanh toán tầng 1', true
),
(
  'Điểm Thu Thủy Tinh - Hai Bà Trưng',
  'scrap_dealer',
  ARRAY['GLASS','METAL_AL']::material_code[],
  21.0133, 105.8521,
  '15 Trần Khát Chân, Hai Bà Trưng, Hà Nội',
  '024 3976 1100', '07:00-17:30', 'Chuyên thu thủy tinh và nhôm, giá cạnh tranh', true
),
(
  'Điểm E-Waste FPT Shop - Hoàng Mai',
  'ewaste',
  ARRAY['ELECTRONIC','BATTERY']::material_code[],
  20.9945, 105.8556,
  'FPT Shop, 68 Giải Phóng, Hoàng Mai, Hà Nội',
  '1800 6600', '09:00-21:00', 'Thu đổi thiết bị cũ, nhận điện thoại, máy tính, tablet', true
),
(
  'Điểm Compost Cộng Đồng - Hà Đông',
  'ngo_dropoff',
  ARRAY['ORGANIC']::material_code[],
  20.9667, 105.7800,
  'Công viên Hà Đông, Hà Đông, Hà Nội',
  '0945 678 901', '06:00-08:30 hàng ngày', 'Dự án compost cộng đồng phường Yết Kiêu', true
),
(
  'Vựa Phế Liệu Tổng Hợp - Long Biên',
  'scrap_dealer',
  ARRAY['PET','HDPE','PP','PAPER','CARDBOARD','METAL_AL','METAL_FE','GLASS','TEXTILE']::material_code[],
  21.0447, 105.8880,
  '88 Nguyễn Văn Cừ, Long Biên, Hà Nội',
  '024 3655 4422', '06:00-18:00', 'Vựa lớn khu vực Long Biên, thu mua tất cả vật liệu tái chế', true
)
on conflict do nothing;
