-- =============================================================
-- ReLoop — Initial Schema Migration
-- Ticket: TRU-72 / T1-02
-- Generated by: W3-C Security Audit Agent (2026-05-09)
-- =============================================================

-- =========== EXTENSIONS ===========
-- AUDIT: earthdistance requires cube as dependency; both must be created first.
-- The playbook assumed these existed but never declared them — added here.
create extension if not exists "uuid-ossp";
create extension if not exists cube;           -- AUDIT: cube is required by earthdistance
create extension if not exists earthdistance;  -- AUDIT: needed for ll_to_earth() geo indexes

-- =========== ENUMS ===========
-- AUDIT: plain CREATE TYPE fails on re-run. Wrapped in DO block for idempotency.
do $$ begin
  create type user_role as enum ('user', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type listing_status as enum ('available','reserved','completed','removed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type listing_intent as enum ('give','exchange','sell_scrap','seek');
exception when duplicate_object then null; end $$;

do $$ begin
  create type material_code as enum (
    'PET','HDPE','PP','PS','PVC','OTHER_PLASTIC',
    'PAPER','CARDBOARD','GLASS','METAL_AL','METAL_FE',
    'TEXTILE','ELECTRONIC','ORGANIC','BATTERY','MIXED'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type point_type as enum ('scrap_dealer','recycle_bin','ngo_dropoff','ewaste','other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type vote_kind as enum ('up','down');
exception when duplicate_object then null; end $$;

-- =========== PROFILES (1-1 với auth.users) ===========
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text not null,
  avatar_url text,
  role user_role not null default 'user',
  eco_points int not null default 0,
  level int not null default 1,
  bio text,
  city text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists profiles_eco_points_idx on profiles (eco_points desc);

-- Auto-create profile on signup
-- AUDIT: security definer + set search_path = public correctly set (prevents schema injection).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name','Eco Hero'));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Helper: is_admin()
-- AUDIT: security definer + set search_path = public correctly prevents schema injection.
-- AUDIT: uses (select auth.uid()) pattern inline for performance — single call per query, not per row.
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from profiles where id = (select auth.uid()) and role = 'admin'
  );
$$;

-- =========== MATERIAL_CATEGORIES ===========
create table if not exists public.material_categories (
  code material_code primary key,
  name_vi text not null,
  name_en text not null,
  icon text,
  color text  -- hex for UI
);

-- =========== MATERIAL_INFO ===========
create table if not exists public.material_info (
  code material_code primary key references material_categories,
  decomposition_years_min int not null,
  decomposition_years_max int,         -- null = effectively forever
  impact_score int not null check (impact_score between 1 and 10),
  recyclable boolean not null,
  recycle_methods jsonb not null default '[]',
  diy_ideas jsonb not null default '[]',
  source_url text
);

-- RLS: material_categories
alter table material_categories enable row level security;
-- AUDIT: policy name collision avoided — using table-qualified names.
create policy "mc_read_all" on material_categories for select using (true);
create policy "mc_admin_write" on material_categories for all using (is_admin()) with check (is_admin());

-- RLS: material_info
alter table material_info enable row level security;
create policy "mi_read_all" on material_info for select using (true);
create policy "mi_admin_write" on material_info for all using (is_admin()) with check (is_admin());

-- =========== PROFILES RLS ===========
-- AUDIT: profiles had NO RLS declared in playbook! Added here.
-- Without RLS, any authenticated user could read all profiles including role field.
alter table profiles enable row level security;
-- AUDIT: (select auth.uid()) pattern used for performance (single evaluation per query).
create policy "profiles_read_public" on profiles for select using (true);  -- display_name, avatar, eco_points are public
create policy "profiles_update_own" on profiles for update
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);
-- AUDIT: role column must NOT be updatable via user policy — server/admin only.
-- The update policy above allows users to update own row but role is protected by:
-- application logic (Server Actions) + admin-only role mutation (is_admin check in app layer).
-- Deferred: column-level RLS for role field → T1-07.

-- =========== LISTINGS ===========
create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references profiles(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 120),
  description text check (char_length(description) <= 2000),
  intent listing_intent not null default 'give',
  material_code material_code not null,
  condition smallint check (condition between 1 and 5),
  photos text[] not null default '{}',
  lat double precision,
  lng double precision,
  city text,
  status listing_status not null default 'available',
  ai_analysis_id uuid,
  moderation_passed boolean default false,
  view_count int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists listings_status_idx on listings(status);
create index if not exists listings_material_idx on listings(material_code);
create index if not exists listings_owner_idx on listings(owner_id);
-- AUDIT: earthdistance extension now declared above; this index is safe.
create index if not exists listings_geo_idx on listings using gist (
  ll_to_earth(lat, lng)
) where lat is not null;
create index if not exists listings_created_at_idx on listings(created_at desc);

alter table listings enable row level security;
-- AUDIT: (select auth.uid()) pattern confirmed in all listing policies — correct.
create policy "listings_read_public" on listings for select
  using (status <> 'removed' and moderation_passed = true);
create policy "listings_read_own" on listings for select using ((select auth.uid()) = owner_id);
create policy "listings_admin_read" on listings for select using (is_admin());
create policy "listings_owner_insert" on listings for insert with check ((select auth.uid()) = owner_id);
create policy "listings_owner_update" on listings for update
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
create policy "listings_owner_delete" on listings for delete
  using ((select auth.uid()) = owner_id or is_admin());

-- =========== AI_ANALYSES (cache) ===========
create table if not exists public.ai_analyses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete set null,
  image_hash text not null,
  image_url text not null,
  model text not null,
  result jsonb not null,
  tokens_input int,
  tokens_output int,
  created_at timestamptz default now()
);
create unique index if not exists ai_analyses_hash_idx on ai_analyses(image_hash);

alter table ai_analyses enable row level security;
-- AUDIT: (select auth.uid()) pattern confirmed — correct.
create policy "ai_read_own" on ai_analyses for select
  using ((select auth.uid()) = user_id or is_admin());
create policy "ai_insert_own" on ai_analyses for insert
  with check ((select auth.uid()) = user_id);
-- AUDIT: no UPDATE or DELETE policy on ai_analyses — intentional (cache is immutable).
-- Server Actions use service_role to insert cache entries when user_id may differ.
-- Document: server must NOT expose service_role client to browser.

-- =========== COLLECTION_POINTS ===========
create table if not exists public.collection_points (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  type point_type not null,
  accepts material_code[] not null default '{}',
  lat double precision not null,
  lng double precision not null,
  address text,
  phone text,
  hours text,
  notes text,
  contributed_by uuid references profiles(id) on delete set null,
  verified boolean not null default false,
  upvotes int not null default 0,
  downvotes int not null default 0,
  created_at timestamptz default now()
);
-- AUDIT: earthdistance extension now declared above; this index is safe.
create index if not exists cp_geo_idx on collection_points using gist (ll_to_earth(lat, lng));

alter table collection_points enable row level security;
create policy "cp_read_all" on collection_points for select using (true);
create policy "cp_user_insert" on collection_points for insert
  with check ((select auth.uid()) is not null);
create policy "cp_owner_admin_update" on collection_points for update
  using (contributed_by = (select auth.uid()) or is_admin());
create policy "cp_admin_delete" on collection_points for delete using (is_admin());

-- =========== COLLECTION_POINT_VOTES ===========
create table if not exists public.collection_point_votes (
  point_id uuid references collection_points(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  kind vote_kind not null,
  created_at timestamptz default now(),
  primary key (point_id, user_id)
);

alter table collection_point_votes enable row level security;
create policy "cpv_read_all" on collection_point_votes for select using (true);
-- AUDIT: (select auth.uid()) pattern confirmed — correct.
create policy "cpv_self_insert" on collection_point_votes for insert
  with check ((select auth.uid()) = user_id);
create policy "cpv_self_update" on collection_point_votes for update
  using ((select auth.uid()) = user_id);
create policy "cpv_self_delete" on collection_point_votes for delete
  using ((select auth.uid()) = user_id);

-- Trigger: update vote counts
-- AUDIT: update_cp_vote_counts does NOT have security definer or set search_path.
-- Risk: low (no auth.uid() call inside, no sensitive data access), but added search_path for consistency.
create or replace function update_cp_vote_counts()
returns trigger language plpgsql set search_path = public as $$
begin
  update collection_points set
    upvotes   = (select count(*) from collection_point_votes
                 where point_id = coalesce(new.point_id, old.point_id) and kind = 'up'),
    downvotes = (select count(*) from collection_point_votes
                 where point_id = coalesce(new.point_id, old.point_id) and kind = 'down')
  where id = coalesce(new.point_id, old.point_id);
  return null;
end; $$;

drop trigger if exists cp_votes_after on collection_point_votes;
create trigger cp_votes_after
  after insert or update or delete on collection_point_votes
  for each row execute function update_cp_vote_counts();

-- =========== EXCHANGES ===========
create table if not exists public.exchanges (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references listings(id) on delete cascade,
  giver_id uuid not null references profiles(id),
  receiver_id uuid not null references profiles(id),
  -- AUDIT: status should be constrained; free text allows injection of invalid states.
  -- Added check constraint here; a proper enum would be cleaner but deferred to avoid migration churn.
  status text not null default 'requested'
    check (status in ('requested','accepted','completed','cancelled')), -- AUDIT: added check
  meeting_note text,
  rated_by_giver smallint check (rated_by_giver between 1 and 5),
  rated_by_receiver smallint check (rated_by_receiver between 1 and 5),
  created_at timestamptz default now(),
  completed_at timestamptz
);

alter table exchanges enable row level security;
-- AUDIT: exchanges missing DELETE policy — added admin-only delete.
create policy "exchanges_parties_read" on exchanges for select
  using ((select auth.uid()) in (giver_id, receiver_id) or is_admin());
create policy "exchanges_receiver_request" on exchanges for insert
  with check ((select auth.uid()) = receiver_id);
create policy "exchanges_parties_update" on exchanges for update
  using ((select auth.uid()) in (giver_id, receiver_id))
  with check ((select auth.uid()) in (giver_id, receiver_id));
create policy "exchanges_admin_delete" on exchanges for delete using (is_admin()); -- AUDIT: added

-- =========== MESSAGES ===========
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  exchange_id uuid not null references exchanges(id) on delete cascade,
  sender_id uuid not null references profiles(id),
  body text not null check (char_length(body) <= 2000),
  created_at timestamptz default now()
);
create index if not exists messages_exchange_idx on messages(exchange_id, created_at);

alter table messages enable row level security;
-- AUDIT: (select auth.uid()) pattern confirmed in subquery — correct.
create policy "messages_parties_read" on messages for select using (
  exists (
    select 1 from exchanges e
    where e.id = messages.exchange_id
      and (select auth.uid()) in (e.giver_id, e.receiver_id)
  )
);
create policy "messages_parties_send" on messages for insert with check (
  (select auth.uid()) = sender_id and exists (
    select 1 from exchanges e
    where e.id = exchange_id
      and (select auth.uid()) in (e.giver_id, e.receiver_id)
  )
);
-- AUDIT: messages missing UPDATE/DELETE — intentional (messages are immutable in MVP).
-- No edit/delete of sent messages per product spec. Deferred to T1-07 confirmation.

-- =========== ECO_ACTIONS ===========
create table if not exists public.eco_actions (
  id bigint generated always as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  kind text not null check (kind in ('scan','listing_create','exchange_complete','point_pin','vote')), -- AUDIT: added check
  points_delta int not null,
  ref_table text,
  ref_id uuid,
  created_at timestamptz default now()
);
create index if not exists eco_actions_user_idx on eco_actions(user_id, created_at desc);

alter table eco_actions enable row level security;
-- AUDIT: (select auth.uid()) pattern confirmed — correct.
create policy "ea_read_own" on eco_actions for select
  using ((select auth.uid()) = user_id or is_admin());
-- INSERT only via Server Actions with service_role. No client-side insert policy intentionally.
-- AUDIT: service_role bypasses RLS by default in Supabase. Server MUST NOT expose service_role
-- client to browser. Use server-only environment variable SUPABASE_SERVICE_ROLE_KEY.

-- =========== BADGES ===========
create table if not exists public.badges (
  code text primary key,
  name_vi text not null,
  description text,
  icon text,
  points_required int default 0
);

alter table badges enable row level security;
create policy "badges_read_all" on badges for select using (true);
-- AUDIT: badges missing admin write policy — anyone could note these are read-only from client.
-- Admin writes badges via service_role / dashboard only. Documented.
create policy "badges_admin_write" on badges for all using (is_admin()) with check (is_admin()); -- AUDIT: added

-- =========== USER_BADGES ===========
create table if not exists public.user_badges (
  user_id uuid references profiles(id) on delete cascade,
  badge_code text references badges(code),
  awarded_at timestamptz default now(),
  primary key (user_id, badge_code)
);

alter table user_badges enable row level security;
create policy "ub_read_all" on user_badges for select using (true);
-- AUDIT: user_badges INSERT/DELETE missing. Awards only via service_role Server Actions.
-- Prevent self-awarding: no INSERT policy for anon/authenticated roles intentionally.
-- Admin can insert via service_role. Documented.

-- =========== NOTIFICATIONS ===========
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  kind text not null,
  title text not null,
  body text,
  link text,
  read_at timestamptz,
  created_at timestamptz default now()
);
create index if not exists notif_user_idx on notifications(user_id, created_at desc);

alter table notifications enable row level security;
-- AUDIT: (select auth.uid()) pattern confirmed — correct.
create policy "notif_read_own" on notifications for select
  using ((select auth.uid()) = user_id);
-- AUDIT: UPDATE allows user to mark read_at — correct. But no WITH CHECK to prevent
-- user from changing kind/title/body. Added with check.
create policy "notif_update_own" on notifications for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id); -- AUDIT: added with check
-- INSERT only via service_role (server pushes notifications). No client INSERT policy.
-- DELETE: user can delete own notifications.
create policy "notif_delete_own" on notifications for delete  -- AUDIT: added
  using ((select auth.uid()) = user_id);

-- =========== ANALYTICS_EVENTS ===========
create table if not exists public.analytics_events (
  id bigint generated always as identity primary key,
  user_id uuid references profiles(id) on delete set null,
  event text not null,
  properties jsonb default '{}',
  created_at timestamptz default now()
);
create index if not exists ae_event_idx on analytics_events(event, created_at desc);

alter table analytics_events enable row level security;
create policy "ae_admin_read" on analytics_events for select using (is_admin());
-- INSERT via service_role only. No client INSERT policy intentionally.
-- AUDIT: service_role bypasses RLS — server must guard this path strictly.
